on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: BUILD
        run: ./localbuild.sh
        
      - name: RPM Build
        id: rpm
        uses: Antikythera/build-rpm@v1
        with:
          spec_file: webssh.spec
          sources: |
            webssh_linux_amd64
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.rpm.outputs.rpm_package_name }}
          path: ${{ steps.rpm.outputs.rpm_package_path }}

      - uses: Shopify/upload-to-release@v2.0.0
        with:
          name: ${{ steps.rpm.outputs.rpm_package_name }}
          path: ${{ steps.rpm.outputs.rpm_package_path }}
